package controller;

public enum MenuCommands {
	APP_QUIT, SHOW_LIST_PARTS, SHOW_DETAIL_PART, ADD_PART, DELETE_PART, SHOW_DETAIL_PERSON_PART, SHOW_LIST_WAREHOUSES, SHOW_DETAIL_WAREHOUSE, ADD_WAREHOUSE, DELETE_WAREHOUSE, 
	SHOW_LIST_INVENTORY, SHOW_DETAIL_INVENTORY, ADD_INVENTORY, DELETE_INVENTORY,
	SHOW_LIST_USERS, SHOW_DETAIL_USER, ADD_USER, DELETE_USER, SHOW_LOGIN, SHOW_LOGOUT,
	PDF_REPORT, EXCEL_REPORT
}
